// HTML report renderer for strapi-security. Self-contained, no deps.
const esc = (s) => String(s ?? "").replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));

const SEV_COLOR = { critical: "#dc2626", high: "#f97316", medium: "#eab308", low: "#3b82f6", info: "#6b7280" };

export function renderHtml(result) {
  const { strapi_url, summary, findings, active_probe, collections_checked } = result;
  const total = findings.length;
  const score = Math.max(0, 100 - (summary.critical * 20 + summary.high * 10 + summary.medium * 4 + summary.low * 1));

  const rows = findings.map((f) => `
    <div style="border-left:4px solid ${SEV_COLOR[f.severity]};background:#fff;padding:14px 18px;border-radius:6px;margin-bottom:12px;box-shadow:0 1px 2px rgba(0,0,0,.06)">
      <div style="display:flex;justify-content:space-between;align-items:center">
        <strong>${esc(f.title)}</strong>
        <span style="background:${SEV_COLOR[f.severity]};color:#fff;font-size:11px;padding:2px 8px;border-radius:10px;text-transform:uppercase">${f.severity}</span>
      </div>
      <div style="color:#374151;font-size:14px;margin:6px 0">${esc(f.explain)}</div>
      <div style="font-size:13px;color:#6b7280"><code>${esc(f.target)}</code></div>
      ${f.probe?.confirmed ? `<div style="font-size:12px;color:#b91c1c;margin-top:4px">✓ CONFIRMED via anonymous probe${f.probe.sample?.total != null ? ` — ${f.probe.sample.total} rows reachable` : ""}</div>` : ""}
      <details style="margin-top:6px"><summary style="cursor:pointer;font-size:13px;font-weight:600;color:#047857">Fix</summary>
        <div style="font-size:13px;background:#f0fdf4;padding:8px;border-radius:4px;margin-top:4px">${esc(f.fix || "")}</div></details>
    </div>`).join("");

  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>strapi-security report — ${esc(strapi_url)}</title>
<style>body{font-family:system-ui,-apple-system,sans-serif;background:#f3f4f6;margin:0;color:#111827}
.wrap{max-width:860px;margin:0 auto;padding:24px}.card{background:#fff;padding:18px;border-radius:8px;box-shadow:0 1px 2px rgba(0,0,0,.06);margin-bottom:18px}
.stat{display:inline-block;text-align:center;margin-right:24px}.stat .n{font-size:30px;font-weight:700}.stat .l{font-size:12px;color:#6b7280}</style></head>
<body><div class="wrap">
  <h1 style="margin:8px 0">🛡️ Strapi Security Report</h1>
  <div style="color:#6b7280;font-size:14px">${esc(strapi_url)} · scored ${score}/100 · ${active_probe.confirmed} leak(s) confirmed live</div>
  <div class="card" style="margin-top:14px">
    <span class="stat"><div class="n" style="color:${SEV_COLOR.critical}">${summary.critical}</div><div class="l">CRITICAL</div></span>
    <span class="stat"><div class="n" style="color:${SEV_COLOR.high}">${summary.high}</div><div class="l">HIGH</div></span>
    <span class="stat"><div class="n" style="color:${SEV_COLOR.medium}">${summary.medium}</div><div class="l">MEDIUM</div></span>
    <span class="stat"><div class="n">${collections_checked.length}</div><div class="l">COLLECTIONS</div></span>
  </div>
  ${total ? rows : `<div class="card">✅ No issues found in the checks run. Re-run after each deploy.</div>`}
  ${(summary.critical + summary.high) > 0 ? `
  <div class="card" style="background:#ecfdf5;border:1px solid #a7f3d0">
    <h2 style="margin:0 0 6px">Want this fixed for you?</h2>
    <p style="font-size:14px;color:#374151;margin:0 0 10px">You have <strong>${summary.critical} critical</strong> and <strong>${summary.high} high</strong> findings. I verify each one live and send a written report with the exact config fixes.</p>
    <a href="https://buy.stripe.com/3cIeVdgikfj47yx9LkcAo0m" style="background:#047857;color:#fff;text-decoration:none;font-size:14px;padding:8px 14px;border-radius:6px">Fixed-scope audit — $99 / 24h</a>
    <a href="https://github.com/Perufitlife/strapi-security" style="color:#047857;font-size:14px;margin-left:10px">See the tool</a>
  </div>` : ""}
  <div style="text-align:center;font-size:12px;color:#9ca3af;padding:8px">
    Generated by <a href="https://github.com/Perufitlife/strapi-security" style="color:#047857">strapi-security</a> · MIT · Runs locally, nothing leaves your machine.
  </div>
</div></body></html>`;
}
